vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO basvloon/luabind
    REF a127bb79b31391bb394ab6d7b03c8de11e72fed3 # 0.9.1-candelic
    SHA512 487927bf519044075bf20d5d2aa1da5779e62f8ecb84e2e997ac500fc5002c409444f1581df46c3c3dde93c4749728ec0e5647347ea09150042bc5e8b198d863
    HEAD_REF master
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
      test   BUILD_WITH_TEST
      docs   BUILD_WITH_DOCS

)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" BUILD_STATIC_LIBS)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" BUILD_SHARED_LIBS)

set(VCPKG_C_FLAGS_DEBUG "${VCPKG_C_FLAGS_DEBUG} -DLUABIND_CPLUSPLUS_LUA")
set(VCPKG_CXX_FLAGS_DEBUG "${VCPKG_CXX_FLAGS_DEBUG} -DLUABIND_CPLUSPLUS_LUA")

set(VCPKG_C_FLAGS_RELEASE "${VCPKG_C_FLAGS_RELEASE} -DLUABIND_CPLUSPLUS_LUA")
set(VCPKG_CXX_FLAGS_RELEASE "${VCPKG_CXX_FLAGS_RELEASE} -DLUABIND_CPLUSPLUS_LUA")

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
	    -DBUILD_TESTING=${BUILD_WITH_TEST}
		-DLUABIND_BUILD_SHARED=${BUILD_SHARED_LIBS}
		-DLUABIND_BUILD_DOCS=${BUILD_WITH_DOCS}
)

file(
    COPY ${SOURCE_PATH}/luabind
    DESTINATION ${CURRENT_PACKAGES_DIR}/include
)

vcpkg_install_cmake()


# Include files should not be duplicated into the /debug/include directory
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

vcpkg_copy_pdbs()

# Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
